apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2017-06-13T14:35:31Z
  generation: 9
  labels:
    run: firewall
  name: firewall
  namespace: default
  resourceVersion: "4631060"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/firewall
  uid: 8d7ce0f3-5045-11e7-8ff2-94de802df35a
spec:
  replicas: 1
  selector:
    run: firewall
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: firewall
    spec:
      containers:
      - image: caiopo/firewall
        imagePullPolicy: IfNotPresent
        name: firewall
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 9
  replicas: 1
