apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-11-10T19:06:10Z
  generation: 3
  labels:
    run: logger
  name: logger
  namespace: default
  resourceVersion: "2698165"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/logger
  uid: bd9b9e19-a778-11e6-857c-94de802df35a
spec:
  replicas: 1
  selector:
    run: logger
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: logger
    spec:
      containers:
      - image: caiopo/logger
        imagePullPolicy: Always
        name: logger
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 3
  replicas: 1
