apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2016-11-07T13:36:27Z
  generation: 9
  labels:
    run: raft
  name: raft
  namespace: default
  resourceVersion: "2611464"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/raft
  uid: 2f35c251-a4ef-11e6-857c-94de802df35a
spec:
  replicas: 0
  selector:
    run: raft
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: raft
    spec:
      containers:
      - image: caiopo/raft
        imagePullPolicy: Always
        name: raft
        resources: {}
        terminationMessagePath: /dev/termination-log
        env:
        - name: RAFT_APP
          value: logger
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 9
  replicas: 0
